### ISSUE TITLE
Undefined Function

### ISSUE THREAD

**Issue by tremayne-stewart** [adeleke5140/audio-transcriber#4]
https://github.com/adeleke5140/audio-transcriber/blob/d1615fb5e201fbc4c5a3dfc4f57e805b9a4263f0/src/app.js#L38

Not sure why this isn't triggering an error when you run it;  maybe because you aren't in strict mode.

**Comment by adeleke5140** [comment]
> https://github.com/adeleke5140/audio-transcriber/blob/d1615fb5e201fbc4c5a3dfc4f57e805b9a4263f0/src/app.js#L38
> 
> 
> 
> Not sure why this isn't triggering an error when you run it;  maybe because you aren't in strict mode. 

I just looked into it and that function doesn't even exists. I will look into it.
I don't believe I am in strict mode either.

**Comment by adeleke5140** [comment]
Found the issue. I had a PR in the works with the fix.
